package hooks_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/buildfoundry-nz/formwork/internal/config"
	"github.com/buildfoundry-nz/formwork/internal/hooks"
	"github.com/buildfoundry-nz/formwork/internal/vcs"
)

func repo(t *testing.T) string {
	t.Helper()
	if _, err := exec.LookPath("git"); err != nil {
		t.Skip("git not available")
	}
	dir := t.TempDir()
	for _, a := range [][]string{{"init", "-q"}, {"config", "user.email", "t@e.com"}, {"config", "user.name", "T"}} {
		if out, err := exec.Command("git", append([]string{"-C", dir}, a...)...).CombinedOutput(); err != nil {
			t.Fatalf("git %v: %v\n%s", a, err, out)
		}
	}
	return dir
}

func TestInstallAndVerify(t *testing.T) {
	dir := repo(t)
	cfg := &config.Config{Lanes: []config.Lane{
		{Name: "pre-commit", Tags: []string{"go"}},
		{Name: "pre-push", All: true},
		{Name: "ci", All: true, CI: true}, // not a git hook → ignored
	}, Rules: []*config.Rule{{ID: "r", Tags: []string{"go"}}}, RuleFiles: 1}

	installed, err := hooks.Install(dir, cfg, false)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(installed, []string{"pre-commit", "pre-push"}) {
		t.Fatalf("installed = %v, want [pre-commit pre-push]", installed)
	}

	if hp, err := vcs.GetConfig(dir, "core.hooksPath"); err != nil || hp != ".formwork/hooks" {
		t.Fatalf("core.hooksPath = %q err=%v", hp, err)
	}

	pc := readShim(t, dir, "pre-commit")
	if !strings.Contains(pc, "check --lane pre-commit --staged") {
		t.Fatalf("pre-commit shim wrong:\n%s", pc)
	}
	// Pin the ARGUMENTS exactly, not a substring of the whole script.
	//
	// The shim deliberately passes no -C: git runs hooks with the working
	// directory set to the repository root, so formwork's default root of "."
	// is already correct. That contract is half of #142 — the other half,
	// vcs.EnsureTopLevel accepting a relative root, is pinned by
	// TestCheckStagedFromRepoRootWithDefaultC in internal/cli.
	//
	// Asserting `!strings.Contains(pc, "-C")` over the rendered script is the
	// weaker test: it passes for a shim that smuggles the root in some other
	// way (`--root`, a cd before exec), which is the case that matters. It was
	// also wrong in the opposite direction until #146 D4 removed the
	// interpolated binary path from the script — that path was part of the
	// string being searched, so an install under /opt/Formwork-CLI/bin failed
	// the test with a message pointing at the wrong thing. Matching the exact
	// argument tail survived that change; the whole script is pinned
	// byte-for-byte by TestShimIsSharableAcrossMachines below.
	const wantArgs = "check --lane pre-commit --staged"
	if got := strings.TrimSpace(pc); !strings.HasSuffix(got, wantArgs) {
		t.Fatalf("pre-commit shim must end in exactly %q (no -C; it relies on git's cwd — see internal/vcs.EnsureTopLevel):\n%s", wantArgs, pc)
	}
	pp := readShim(t, dir, "pre-push")
	if !strings.Contains(pp, "check --lane pre-push") || strings.Contains(pp, "--staged") {
		t.Fatalf("pre-push shim wrong (should not be --staged):\n%s", pp)
	}
	if fi, _ := os.Stat(filepath.Join(dir, ".formwork", "hooks", "pre-commit")); fi.Mode()&0o111 == 0 {
		t.Fatal("shim is not executable")
	}

	if p, err := hooks.Verify(dir, cfg); err != nil || len(p) != 0 {
		t.Fatalf("verify reported problems right after install: %v (err=%v)", p, err)
	}
}

// The generated shim is a SHARED, COMMITTED artifact (#146 D4), so its bytes
// must not depend on the machine that generated it. An interpolated absolute
// binary path made every install produce a different file: committing it wired
// the whole team to one developer's `/Users/<name>/go/bin/formwork`, and leaving
// it uncommitted meant every clone had no gate until someone remembered to run
// install. Neither is a gate a repository can share.
//
// Asserted byte-for-byte rather than by substring, because "constant" is the
// property being claimed: a later step of #146 makes `hooks verify` reject a
// shim whose bytes differ from what install would write, which is only possible
// while there is exactly one right answer per lane.
//
// Accepted cost, and it is deliberate: the hook now resolves `formwork` on PATH,
// so a developer without it on PATH gets exit 127 and a blocked commit — loud
// and fail-closed, not a silent pass.
func TestShimIsSharableAcrossMachines(t *testing.T) {
	dir := repo(t)
	cfg := &config.Config{Lanes: []config.Lane{
		{Name: "pre-commit", All: true},
		{Name: "pre-push", All: true},
	}, Rules: []*config.Rule{{ID: "r"}}, RuleFiles: 1}

	if _, err := hooks.Install(dir, cfg, false); err != nil {
		t.Fatal(err)
	}

	for _, tc := range []struct{ lane, want string }{
		{"pre-commit", "#!/bin/sh\n" +
			"# generated by 'formwork hooks install' — do not edit\n" +
			"exec formwork check --lane pre-commit --staged\n"},
		{"pre-push", "#!/bin/sh\n" +
			"# generated by 'formwork hooks install' — do not edit\n" +
			"exec formwork check --lane pre-push\n"},
	} {
		if got := readShim(t, dir, tc.lane); got != tc.want {
			t.Errorf("%s shim is not the shareable form:\ngot:\n%s\nwant:\n%s", tc.lane, got, tc.want)
		}
	}
}

func TestVerifyFailsBeforeInstall(t *testing.T) {
	dir := repo(t)
	cfg := &config.Config{Lanes: []config.Lane{{Name: "pre-commit", All: true}}, Rules: []*config.Rule{{ID: "r"}}, RuleFiles: 1}
	if p, err := hooks.Verify(dir, cfg); err != nil || len(p) == 0 {
		t.Fatalf("verify should report problems before install: %v (err=%v)", p, err)
	}
}

func TestInstallNoGitHookLanesErrors(t *testing.T) {
	dir := repo(t)
	cfg := &config.Config{Lanes: []config.Lane{{Name: "ci", All: true, CI: true}}}
	if _, err := hooks.Install(dir, cfg, false); err == nil {
		t.Fatal("expected an error when no lane maps to a git hook")
	}
}

func TestInstallIsIdempotent(t *testing.T) {
	dir := repo(t)
	cfg := &config.Config{Lanes: []config.Lane{{Name: "pre-commit", All: true}}, Rules: []*config.Rule{{ID: "r"}}, RuleFiles: 1}
	if _, err := hooks.Install(dir, cfg, false); err != nil {
		t.Fatal(err)
	}
	if _, err := hooks.Install(dir, cfg, false); err != nil {
		t.Fatalf("second install should succeed: %v", err)
	}
	if p, err := hooks.Verify(dir, cfg); err != nil || len(p) != 0 {
		t.Fatalf("verify after re-install: %v (err=%v)", p, err)
	}
}

func readShim(t *testing.T, dir, name string) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(dir, ".formwork", "hooks", name))
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

// A git-hook lane that selects no rules is a wiring defect, not a healthy
// install. The shim runs `formwork check --lane <name>`, which refuses an empty
// lane (exit 2, #151 row 10) — so installing one produces a hook that aborts
// EVERY commit, with nothing in the hook's output the developer can act on.
//
// Before this guard, install printed "installed git hooks: pre-commit" and
// verify printed "hooks wired", both exit 0, while no commit could be made. The
// two commands whose entire job is certifying the wiring — one of which replaces
// the shell system's hooks-wired CI gate — both certified it.
func TestInstallRefusesAGitHookLaneThatSelectsNoRules(t *testing.T) {
	dir := repo(t)
	cfg := &config.Config{
		Lanes:     []config.Lane{{Name: "pre-commit", Tags: []string{"sql"}}},
		Rules:     []*config.Rule{{ID: "r", Tags: []string{"go"}}}, // no sql-tagged rule
		RuleFiles: 1,
	}
	_, err := hooks.Install(dir, cfg, false)
	if err == nil {
		t.Fatal("installed a hook that would abort every commit")
	}
	if !strings.Contains(err.Error(), "pre-commit") {
		t.Errorf("the error must name the lane: %v", err)
	}

	// Verify must agree. A hook wired by an older binary is still installed on
	// disk, so verify has to report the condition independently of install.
	problems, err := hooks.Verify(dir, cfg)
	if err != nil {
		t.Fatal(err)
	}
	if len(problems) == 0 {
		t.Fatal("verify reported the wiring healthy")
	}
	found := false
	for _, p := range problems {
		if strings.Contains(p, "selects no rules") {
			found = true
		}
	}
	if !found {
		t.Errorf("verify did not name the empty lane: %v", problems)
	}
}
