// Package hooks installs and verifies git hook shims that invoke formwork
// lanes (spec §8). `formwork hooks install` points git's core.hooksPath at a
// generated shim directory; `formwork hooks verify` replaces the shell system's
// "hooks-wired" gate. A lane is wired as a git hook when its name is a git
// client-hook name (pre-commit, pre-push, pre-merge-commit).
package hooks

import (
	"sort"
	"strings"

	"github.com/buildfoundry-nz/formwork/internal/config"
)

// hooksDir is the core.hooksPath value formwork manages (repo-relative).
const hooksDir = ".formwork/hooks"

// generatedMarker is the second line of every shim shim() renders: the mark
// that says formwork wrote this file, as opposed to an operator having put it
// in the managed directory. It is named rather than inlined because a marker
// spelled as a literal in three files is one edit away from three files
// disagreeing about what formwork's own output looks like.
const generatedMarker = "# generated by 'formwork hooks install' — do not edit"

// isGenerated reports whether these bytes are output `formwork hooks install`
// wrote, judged by the marker above.
//
// ONE PREDICATE, TWO READERS, AND THEY PAY DIFFERENT PRICES FOR THE ANSWER.
// verify.go's orphanProblems uses it to choose the wording of a report;
// install.go's orphanCleanup uses it to decide whether to DELETE the file. A
// second spelling of "formwork wrote this" would therefore be a second answer to
// the question of which of an operator's files may be removed, which is why the
// test lives here rather than at either call site.
func isGenerated(b []byte) bool { return strings.Contains(string(b), generatedMarker) }

// wiredHookNames are the client-side hooks a lane may be wired to.
//
// Deliberately NOT the set of names git will execute — that is
// gitClientHookNames in foreign.go, which is much larger and answers a
// different question. Both sets are consulted in this package and confusing
// them narrows either what formwork wires or what it is willing to overwrite,
// so neither is spelled in a way the other can be reached for by accident.
var wiredHookNames = map[string]bool{
	"pre-commit":       true,
	"pre-push":         true,
	"pre-merge-commit": true,
}

// Expected returns, sorted, the lane names in cfg that map to git hooks.
func Expected(cfg *config.Config) []string {
	var out []string
	for _, l := range cfg.Lanes {
		if wiredHookNames[l.Name] {
			out = append(out, l.Name)
		}
	}
	sort.Strings(out)
	return out
}

// emptyLanes returns, sorted, the git-hook lanes in cfg that select no rules.
//
// This is a precondition of the shim, not a style preference. The generated
// hook runs `formwork check --lane <name>`, and check refuses a lane that
// selects nothing (exit 2, #151 row 10) — correctly, since a lane wired into a
// hook and silently running zero rules is a gate that only looks like one. But
// that refusal reaches the developer as an ABORTED COMMIT, every commit, with
// nothing to do about it, while the two commands whose whole job is certifying
// the wiring said it was healthy. install and verify own that precondition
// because they are the only place `check --lane` call sites are generated; the
// alternative is an adopter who cannot commit and is told the hooks are fine.
func emptyLanes(cfg *config.Config) []string {
	var out []string
	for _, name := range Expected(cfg) {
		rls, err := cfg.RulesForLane(name)
		if err != nil || len(rls) == 0 {
			out = append(out, name)
		}
	}
	return out
}

// fileSetFlag is the change-restriction a hook passes to `formwork check`.
// Only pre-commit runs against the staged set; the others run the full tree.
func fileSetFlag(hook string) string {
	if hook == "pre-commit" {
		return " --staged"
	}
	return ""
}

// shim renders one hook script. Its output depends on nothing but the lane, so
// every machine generates the same bytes and the result can be committed and
// shared like any other tracked file (#146 D4) — where an interpolated absolute
// binary path made each install machine-specific, and a shim that cannot be
// committed leaves every fresh clone ungated until someone runs install.
//
// It resolves `formwork` on PATH. Accepted cost: without formwork on PATH the
// hook exits 127 and the commit is blocked — loud and fail-closed, which is the
// direction this repo errs in.
//
// It deliberately passes no -C: git runs hooks with the working directory set
// to the repository root, so formwork's default root of "." is already correct.
//
// That contract is load-bearing and was once broken on the other side —
// vcs.EnsureTopLevel could not accept a relative root, so every generated hook
// exited 2 on every commit (#142). If you change either half, the pairing is
// pinned by TestCheckStagedFromRepoRootWithDefaultC in internal/cli, and by the
// exact-argument assertion in TestInstallAndVerify here.
//
// THE CONTRACT HOLDS ONLY WHEN THE FORMWORK ROOT IS THE GIT TOP LEVEL, and both
// commands now say so instead of assuming it. This comment recorded a KNOWN GAP
// (#146) where install wrote a shim under a subdirectory while setting a
// repo-relative core.hooksPath git resolves from the top level, so the hook was
// never found: install refuses that root now (preflight.go, D1). This sentence
// used to carry an exception for an ambient GIT_DIR, which emptied the
// `--show-prefix` that refusal reads; #167 closed it — internal/vcs removes the
// pointer family from every git command, and
// TestInstallStillRefusesASubdirectoryUnderAnAmbientGitDir re-measures that. The
// spelling that survived it was inside FORMWORK_GIT_ENV=inherit, where the
// removal is deliberately off and GIT_WORK_TREE could name a subdirectory git
// then reports as the top level; unregisteredWorkTreeRefusal (preflight.go)
// refuses that state, on git's own worktree registry rather than on the prefix
// (#179). And verify reads
// the directory git names, so it exits 1 wherever an older binary
// or a hand-set config left the state behind — pinned by
// TestVerifyReportsShimsGitWillNeverFind.
func shim(lane string) string {
	return "#!/bin/sh\n" +
		generatedMarker + "\n" +
		"exec " + checkCommand(lane) + "\n"
}

// checkCommand is the formwork invocation one lane's hook makes.
//
// It has two readers and they must not drift: shim above, which writes it into
// the generated hook, and preflight.go's chainingRemedy, which prints it as the
// line to add to a hook formwork refuses to replace. Advice that differs from
// what formwork itself would run is advice the operator debugs instead of the
// problem.
// #81 In: bullet 3 / #338 — DECIDED: hooks install does NOT emit --skip-escapes,
// and --skip-escapes keeps its false default (internal/cli/cli.go).
//
// The case is real. #81 measured it: the machine-wide heavy gate governs only
// rules.ProcessBoundOf rules — 3 of 221 real command rules by PR #245's census
// — so the other ~218 heavy escapes run at full --workers in every one of N
// parallel checkouts. 8 concurrent `formwork check` runs with 6 CostHeavy
// command rules each put 48 subprocesses on the machine in 1.15s wall.
//
// Emitting --skip-escapes here would fix that by making every installed
// pre-commit hook stop running heavy rules. That is not a bound, it is a
// silent narrowing of what the gate judges, applied to every consumer at
// install time and visible in no output: the hook would report a pass having
// declined to look, which is the defect class this repository exists to catch.
// The same argument rejects flipping the flag's default, which would narrow it
// for CI too.
//
// The lever that does bound it without narrowing anything is per-lane `cost:`
// filters — an operator states which lanes carry heavy rules, and the hook
// runs a lane that is cheap by construction rather than a lane that is
// expensive and skipped. That is a config decision the consumer owns, and its
// schema — `cost: fast | heavy` declared on a lane — is documented in
// docs/reference.md's Lanes section. `formwork check --help` carries the flag
// side of the same argument: it names --lane, and --skip-escapes's own help
// text states the position this decision keeps — "run them in CI, not local
// hooks". Anyone revisiting this should move that argument, not delete it.
//
// The pointer above is held by decision_citation_test.go, which reads the
// section it names and fails if that section does not document `cost:` — a
// decision that refuses one lever and misdirects the reader to the other is
// half a decision (#338).
func checkCommand(lane string) string {
	return "formwork check --lane " + lane + fileSetFlag(lane)
}
