// scopedeclare_test.go — scope.not_declaring end to end: a rule loaded from
// YAML, a real walked tree, engine.Run, and the finding that must not be there.
//
// Its own file rather than engine_test.go's memFileSet: the whole point of this
// key is that the verdict comes from a file's CONTENT, so the test has to hand
// the engine real files whose bytes differ while their names do not carry the
// answer. Every file here is `**/*.go` under the same directory — if the skip
// were secretly keyed on path, all three would share one verdict.
package engine_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/buildfoundry-nz/formwork/internal/config"
	"github.com/buildfoundry-nz/formwork/internal/engine"
	"github.com/buildfoundry-nz/formwork/internal/scan"
)

// declTree writes a repo whose one rule bans WIDGET in every .go file and
// declines files declaring the generator marker, then returns the loaded rules
// and the walked tree.
func declTree(t *testing.T, notDeclaring string, files map[string]string) ([]*config.Rule, *scan.FileSet) {
	t.Helper()
	root := t.TempDir()
	all := map[string]string{
		".formwork/formwork.yaml": "version: 1\n",
		".formwork/rules/r.yaml": "rules:\n  - id: no-widget\n    type: forbidden-pattern\n" +
			"    severity: error\n    scope:\n      include: ['**/*.go']\n" + notDeclaring +
			"    params: {pattern: WIDGET}\n    cure: do not\n",
	}
	for k, v := range files {
		all[k] = v
	}
	for rel, content := range all {
		p := filepath.Join(root, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	cfg, err := config.Load(root)
	if err != nil {
		t.Fatal(err)
	}
	fset, err := scan.Walk(root)
	if err != nil {
		t.Fatal(err)
	}
	return cfg.Rules, fset
}

const (
	genBody  = "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage p\n\nconst A = \"WIDGET\"\n"
	handBody = "package p\n\nconst B = \"WIDGET\"\n"
)

// The load-bearing assertion, and it needs BOTH halves. A test that only
// checked the generated file was skipped would pass just as well on a rule that
// had stopped matching anything — which is the failure mode this key could
// plausibly introduce, since it is the first scope test that reads bytes.
func TestRunNotDeclaringSkipsOnlyTheDeclaringFile(t *testing.T) {
	rs, fset := declTree(t, "      not_declaring: ['DO NOT EDIT.']\n", map[string]string{
		"gen.go":  genBody,
		"hand.go": handBody,
	})
	got, err := engine.Run(rs, fset, 1)
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 1 {
		t.Fatalf("findings = %+v, want exactly 1 — the hand-authored file only", got)
	}
	if got[0].Path != "hand.go" {
		t.Fatalf("finding on %q, want hand.go: the generated file declared itself out and the authored one did not", got[0].Path)
	}
}

// Without the key, the same tree yields the same rule judging both files. This
// is the control: it proves the single finding above is the key working rather
// than the rule being broken, misscoped, or the pattern never matching.
func TestRunWithoutNotDeclaringJudgesBothFiles(t *testing.T) {
	rs, fset := declTree(t, "", map[string]string{
		"gen.go":  genBody,
		"hand.go": handBody,
	})
	got, err := engine.Run(rs, fset, 1)
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 2 {
		t.Fatalf("findings = %+v, want 2 — with no declaration key the generator marker means nothing to scope", got)
	}
}

// A marker that matches nothing must change nothing. An entry whose subject
// left is the dead-exclude failure in a new shape, and it has to read as
// "protects nothing" rather than quietly narrowing the rule.
func TestRunNotDeclaringMatchingNothingIsInert(t *testing.T) {
	rs, fset := declTree(t, "      not_declaring: ['GENERATED BY A TOOL THAT NEVER RAN']\n", map[string]string{
		"gen.go":  genBody,
		"hand.go": handBody,
	})
	got, err := engine.Run(rs, fset, 1)
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 2 {
		t.Fatalf("findings = %+v, want 2 — a marker no file declares must subtract nothing", got)
	}
}
