// scopedeclare.go — scope.not_declaring: the declaration-keyed half of scope.
// Split from config.go, which the 750-line vendor cap bounds; same package.
//
// WHY A DECLARATION IS NOT A PATH. Every other scope key answers "where does
// this file sit". That is the wrong question for the largest class of
// non-authored files in a real repository — generator output. Answering it by
// location means every rule that must not judge generated code carries a list
// of globs naming today's generator layout: `**/*.g.dart`, `**/*.pb.go`,
// `**/*.freezed.dart`, `shared/generated/**`, one entry per spelling per rule.
// Those lists are permitted-SETS by shape: a region a rule does not look at,
// which is exactly where the next violation gets parked, and adding a
// generator (or renaming an output suffix) silently widens or strands them.
//
// A generated file already says what it is, in its first line, because every
// generator writes the marker: `// Code generated by protoc-gen-go. DO NOT
// EDIT.` So the rule can key on what the file DECLARES instead of on where it
// sits — one marker per rule, no glob list, and a new generator is covered on
// the day it lands rather than when someone remembers to add its suffix.
//
// WHY THIS IS NOT AN HONOUR SYSTEM, which is the obvious objection. A marker a
// file writes about itself could be written into a hand-authored file to buy an
// exemption. That attack is real and this key does not defeat it alone — it is
// defeated by the codegen-freshness gates an adopting repo already runs, which
// assert that every file bearing the marker REPRODUCES from its generator. A
// hand-authored file wearing the marker fails those. So the declaration is a
// CHECKED claim, not a self-granted one, and that is the difference between
// this key and the glob list it replaces: a glob cannot be checked against
// anything, and nothing detects a file moved into its region.
//
// The key therefore subtracts scope like except.paths does, and like
// except.paths it is reported with live match counts rather than silently — an
// entry matching nothing is a lie the census prints, not a protection nobody
// can see.
package config

import (
	"bytes"
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

// parseNotDeclaring decodes the scope.not_declaring node: a sequence of literal
// markers. An absent key yields nil — the behaviour that predates it.
//
// Every failure mode here is an edit that did not finish, and the alternative
// to refusing it is a rule that silently judges (or silently skips) a class the
// author thought they had named:
//
//   - a non-sequence node, including a bare string, because `not_declaring:
//     "Code generated"` reads as one marker to a human and decodes to a
//     different shape;
//   - a non-scalar entry;
//   - an empty or whitespace-only marker, which `bytes.Contains` matches in
//     EVERY file — a rule scoped to nothing at all, the fail-open direction.
func parseNotDeclaring(n yaml.Node) ([]string, error) {
	if n.Kind == 0 {
		return nil, nil
	}
	if n.Kind != yaml.SequenceNode {
		return nil, fmt.Errorf("want a sequence of literal markers, got kind %v", n.Kind)
	}
	out := make([]string, 0, len(n.Content))
	for _, item := range n.Content {
		if item.Kind != yaml.ScalarNode {
			return nil, fmt.Errorf("entry must be a string marker, got kind %v", item.Kind)
		}
		if strings.TrimSpace(item.Value) == "" {
			return nil, fmt.Errorf("entry is empty; an empty marker matches every file, which scopes the rule to nothing")
		}
		out = append(out, item.Value)
	}
	return out, nil
}

// NotDeclaring returns this rule's scope.not_declaring markers (read-only; do
// not mutate). Empty when the rule declares none. Used by the escape-hatch
// census so the key is never a silent subtraction.
func (r *Rule) NotDeclaring() []string {
	return r.notDeclaring
}

// DeclinedBy reports which scope.not_declaring marker removed a file with this
// content from the rule's evaluation, and whether any did.
//
// Content, not path: this is the one scope test that cannot be answered from a
// file name. Callers hold the bytes already — the engine reads every file it
// evaluates — so this costs a substring scan, and only for rules that declare
// the key.
//
// The marker is matched as a LITERAL, not a pattern. A generator's line is
// fixed text it emits verbatim, and a regexp here would make the difference
// between "declares this" and "mentions this" depend on metacharacters nobody
// intended to write.
func (r *Rule) DeclinedBy(content []byte) (string, bool) {
	for _, m := range r.notDeclaring {
		if bytes.Contains(content, []byte(m)) {
			return m, true
		}
	}
	return "", false
}
