package config_test

import (
	"strings"
	"testing"

	"github.com/buildfoundry-nz/formwork/internal/config"
)

// scope.not_declaring is the declaration-keyed half of scope: the one scope
// test a path cannot answer. These pin the LOAD half — what the key decodes to,
// what it refuses, and that a file's own declaration is what removes it.
//
// The generator marker is the motivating case. A repo that must not judge
// generated output otherwise carries `**/*.g.dart`, `**/*.pb.go`,
// `**/*.freezed.dart`, `shared/generated/**` … on every such rule: permitted-
// SETS by shape, one per generator spelling, which a new generator silently
// escapes and a renamed suffix silently strands.

func declRepo(t *testing.T, scope string) string {
	t.Helper()
	return writeRepo(t, map[string]string{
		".formwork/formwork.yaml": validRoot,
		".formwork/rules/r.yaml": "rules:\n  - id: no-widget\n    type: forbidden-pattern\n" +
			"    scope: " + scope + "\n    params: {pattern: WIDGET}\n",
	})
}

func TestScopeNotDeclaringDefaultsToNone(t *testing.T) {
	cfg, err := config.Load(declRepo(t, "{include: ['**/*.go']}"))
	if err != nil {
		t.Fatal(err)
	}
	if got := cfg.Rules[0].NotDeclaring(); len(got) != 0 {
		t.Fatalf("NotDeclaring() = %v, want empty — an undeclared key must leave the rule exactly as it was", got)
	}
}

func TestScopeNotDeclaringIsCarried(t *testing.T) {
	cfg, err := config.Load(declRepo(t, "{include: ['**/*.go'], not_declaring: ['Code generated by protoc-gen-go. DO NOT EDIT.']}"))
	if err != nil {
		t.Fatal(err)
	}
	got := cfg.Rules[0].NotDeclaring()
	if len(got) != 1 || got[0] != "Code generated by protoc-gen-go. DO NOT EDIT." {
		t.Fatalf("NotDeclaring() = %v, want the one marker verbatim", got)
	}
}

// The whole point: a file that DECLARES the marker is out, one that does not is
// in, and neither answer came from the file's name. Both sides are asserted —
// a test that only checks the skip would pass on a rule that had stopped
// matching anything at all.
func TestDeclinedByKeysOnContentNotPath(t *testing.T) {
	cfg, err := config.Load(declRepo(t, "{include: ['**/*.go'], not_declaring: ['DO NOT EDIT.']}"))
	if err != nil {
		t.Fatal(err)
	}
	r := cfg.Rules[0]

	gen := []byte("// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage p\n\nconst X = \"WIDGET\"\n")
	marker, declined := r.DeclinedBy(gen)
	if !declined {
		t.Fatal("DeclinedBy(generated content) = false, want true: the file declares the marker")
	}
	if marker != "DO NOT EDIT." {
		t.Fatalf("DeclinedBy returned marker %q, want the matched marker so a census can name it", marker)
	}

	hand := []byte("package p\n\nconst X = \"WIDGET\"\n")
	if _, declined := r.DeclinedBy(hand); declined {
		t.Fatal("DeclinedBy(hand-authored content) = true, want false: nothing in it declares the marker")
	}
}

// A path that Applies() covers must stay covered: not_declaring subtracts on
// content alone and must not quietly change the path test.
func TestNotDeclaringDoesNotAlterPathScope(t *testing.T) {
	cfg, err := config.Load(declRepo(t, "{include: ['**/*.go'], not_declaring: ['DO NOT EDIT.']}"))
	if err != nil {
		t.Fatal(err)
	}
	r := cfg.Rules[0]
	if !r.Applies("api/thing.go") {
		t.Fatal("Applies(api/thing.go) = false, want true — not_declaring must not narrow the path scope")
	}
	if r.Applies("api/thing.dart") {
		t.Fatal("Applies(api/thing.dart) = true, want false — include still governs")
	}
}

// Every refusal below is an edit that did not finish. The empty-marker case is
// the load-bearing one: bytes.Contains matches an empty string in EVERY file,
// so accepting it scopes the rule to nothing while reading as a narrow carve-out.
func TestLoadRejectsBadScopeNotDeclaring(t *testing.T) {
	for _, tc := range []struct{ name, scope, want string }{
		{
			name:  "bare string instead of a sequence",
			scope: "{include: ['**/*.go'], not_declaring: 'DO NOT EDIT.'}",
			want:  "want a sequence",
		},
		{
			name:  "empty marker matches every file",
			scope: "{include: ['**/*.go'], not_declaring: ['']}",
			want:  "matches every file",
		},
		{
			name:  "whitespace-only marker",
			scope: "{include: ['**/*.go'], not_declaring: ['   ']}",
			want:  "matches every file",
		},
		{
			name:  "non-scalar entry",
			scope: "{include: ['**/*.go'], not_declaring: [['DO NOT EDIT.']]}",
			want:  "must be a string marker",
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			_, err := config.Load(declRepo(t, tc.scope))
			if err == nil {
				t.Fatalf("Load succeeded; want a refusal mentioning %q", tc.want)
			}
			if !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("Load error = %q, want it to mention %q", err, tc.want)
			}
			if !strings.Contains(err.Error(), "scope.not_declaring") {
				t.Fatalf("Load error = %q, want it to name the key so the operator knows which line to fix", err)
			}
		})
	}
}
