package main

// fixtureinventory_registry_conformance_test.go — the same RENDER-NORMALISATION
// obligation as the live-include registry, one level over (#13521, #15918).
//
// Same scope and same limit as its sibling, for the same reason: this test
// reads each committed INVENTORY.tsv and re-renders WHAT IT JUST READ, so the
// expected side derives from the artifact under test. It proves ordering,
// dedup and header/trailing-newline form; it cannot prove the manifest lists
// the fixture directories that actually exist, because the directories are
// never enumerated for comparison here.
//
// That second invariant is enforced at census time instead — FIXTURE-REMOVED
// for a row whose directory is gone, FIXTURE-UNTRACKED for a directory with no
// row — which is also why the `!found` branch below skips rather than fails.
// See inventory_registry_conformance_test.go's header for the full argument.
//
// .formwork/fixtures/<rule-id>/INVENTORY.tsv drifted from its writer for the same
// reason and in the same four shapes, and it drifted further: 8 of the committed
// manifests carried no header block at all. Both registries are regenerated by
// the one --write-inventory command, so a corpus that conforms on only one side
// still hands the author a diff full of files they do not own.
//
// Kept in its own file rather than folded in beside the live-include half, for
// two reasons that happen to agree. The 400-line test cap applies repo-wide, and
// a test file whose name derives from no impl stem pairs by DIRECTORY — it would
// become the TDD companion of all thirteen census sources instead of the one file
// it is about. Named from fixtureinventory.go, it pairs with fixtureinventory.go.

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"
)

// TestFixtureManifestCorpusIsRenderNormalised pins every committed fixture
// manifest to the renderer's output for the rows it already contains. Same
// guarantee, same limit, same cure, same #13521 — see the file header.
func TestFixtureManifestCorpusIsRenderNormalised(t *testing.T) {
	root := repoRoot(t)
	fixturesRoot := filepath.Join(root, filepath.FromSlash(fixturesRootRel))
	rules, err := os.ReadDir(fixturesRoot)
	if err != nil {
		t.Fatalf("reading %s: %v", fixturesRootRel, err)
	}

	checked, drifted := 0, 0
	for _, r := range rules {
		if !r.IsDir() {
			continue
		}
		rel := fixtureManifestRel(r.Name())
		abs := filepath.Join(root, filepath.FromSlash(rel))

		dirs, found, err := readFixtureManifest(root, r.Name())
		if err != nil {
			t.Fatalf("%s: %v", rel, err)
		}
		// A rule with no manifest answers through FIXTURE-UNTRACKED at census
		// time; it is not this test's finding, and treating it as one would
		// report a single fact as two offences.
		if !found {
			continue
		}
		got, err := os.ReadFile(abs)
		if err != nil {
			t.Fatalf("read %s: %v", rel, err)
		}
		checked++
		if bytes.Equal(got, renderFixtureManifest(dirs)) {
			continue
		}
		drifted++
		if drifted <= driftReportCap {
			t.Errorf("%s is not RENDER-NORMALISED, so running the printed cure rewrites it for an "+
				"author who never touched this rule (#13521). This is NOT a staleness check: a row "+
				"whose directory is gone is FIXTURE-REMOVED at census time, and a directory with no "+
				"row is FIXTURE-UNTRACKED. Re-render the corpus with:\n"+
				"  go run -C tools/formwork-vacuity-census . --write-inventory <repo-root>", rel)
		}
	}

	if checked == 0 {
		t.Fatalf("no %s was read under %s — the walk proved nothing", fixtureManifestName, fixturesRootRel)
	}
	if drifted > driftReportCap {
		t.Errorf("and %d further manifests differ — %d of %d checked", drifted-driftReportCap, drifted, checked)
	}
}
